# NOT a production image
FROM node:24-alpine
WORKDIR /app

RUN apk add --no-cache postgresql-client netcat-openbsd

COPY package.json package-lock.json* syncDevDeps.sh ./
RUN sh ./syncDevDeps.sh

COPY . .

ENV NODE_ENV=development

EXPOSE 5312
RUN chmod +x ./validateEnvs.sh 

ENTRYPOINT ["./validateEnvs.sh"]
