/*
 * Copyright © 2026 Fells Code, LLC
 * Licensed under the GNU Affero General Public License v3.0
 * See LICENSE file in the project root for full license information
 */

/**
 * Emits the OpenAPI document and the typed client from the live route definitions.
 *
 * The registry is populated as a side effect of importing the route modules, which is
 * why this loads routes into a throwaway Express app rather than reading a checked-in
 * spec. No environment or database is needed: route modules only register metadata at
 * import time.
 *
 * Run with `npm run generate:api`. Both outputs are committed, so a contract change
 * shows up as a reviewable diff.
 */

import express from 'express';
import { mkdir, writeFile } from 'fs/promises';
import openapiTS, { astToString } from 'openapi-typescript';
import path from 'path';
import { format, resolveConfig } from 'prettier';

import { loadRoutes } from '../lib/loadRoutes.js';
import { generateOpenApiDocument } from '../openapi/document.js';

const LICENSE_HEADER = `/*
 * Copyright © 2026 Fells Code, LLC
 * Licensed under the GNU Affero General Public License v3.0
 * See LICENSE file in the project root for full license information
 */
`;

const GENERATED_NOTICE = `
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 *
 * Regenerate with \`npm run generate:api\`.
 */
`;

const SPEC_PATH = path.resolve(process.cwd(), 'openapi.json');
const TYPES_PATH = path.resolve(process.cwd(), 'src/generated/api.ts');

// Formatted here rather than left to the commit hook, so regenerating never leaves the
// tree failing `format:check`.
async function formatAs(contents: string, filepath: string) {
  return format(contents, { ...(await resolveConfig(filepath)), filepath });
}

export async function buildOpenApiDocument() {
  await loadRoutes(express());

  return generateOpenApiDocument();
}

export async function generateApiTypes() {
  const document = await buildOpenApiDocument();
  const pathCount = Object.keys(document.paths ?? {}).length;

  if (pathCount === 0) {
    throw new Error('Refusing to write an empty spec: no routes were registered.');
  }

  const ast = await openapiTS(document as Parameters<typeof openapiTS>[0]);
  const types = `${LICENSE_HEADER}${GENERATED_NOTICE}\n${astToString(ast)}`;

  await mkdir(path.dirname(TYPES_PATH), { recursive: true });
  await writeFile(SPEC_PATH, await formatAs(JSON.stringify(document), SPEC_PATH));
  await writeFile(TYPES_PATH, await formatAs(types, TYPES_PATH));

  return { pathCount, specPath: SPEC_PATH, typesPath: TYPES_PATH };
}

const invokedDirectly = process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]));

if (invokedDirectly) {
  const { pathCount } = await generateApiTypes();
  console.log(`Generated openapi.json and src/generated/api.ts from ${pathCount} paths.`);
}
