name: Bug report
description: Report a bug or unexpected behavior in Seamless Auth API
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Seamless Auth API is security-sensitive,
        so clear and complete reports help a lot.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen.
      placeholder: A clear and concise description of the issue.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Provide steps or a minimal reproduction.
      placeholder: |
        1. Configure environment with...
        2. Call endpoint...
        3. Observe error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / error output
      description: Paste relevant logs. Redact secrets.
      render: shell

  - type: input
    id: version
    attributes:
      label: Version / commit
      placeholder: v0.1.0 or commit hash

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Local development
        - Self-hosted (production)
        - SeamlessAuth Cloud
