/*
 * Copyright © 2026 Fells Code, LLC
 * Licensed under the GNU Affero General Public License v3.0
 * See LICENSE file in the project root for full license information
 */

// src/schemas/authEvent.types.ts
import { z } from 'zod';

export const AUTH_EVENT_TYPES = [
  'auth_action_incremented',
  'bearer_token_failed',
  'bearer_token_success',
  'bearer_token_suspicious',
  'bootstrap_admin_check_skipped',
  'bootstrap_admin_granted',
  'cookie_token_failed',
  'cookie_token_success',
  'cookie_token_suspicious',
  'credentials_deleted',
  'informational',
  'internal_user_updated_by_owner',
  'jwks_failed',
  'jwks_success',
  'jwks_suspicious',
  'login_challenge',
  'login_failed',
  'login_success',
  'login_suspicious',
  'logout_failed',
  'logout_success',
  'logout_suspicious',
  'magic_link_poll_completed_successfully',
  'magic_link_requested',
  'magic_link_success',
  'mfa_otp_failed',
  'mfa_otp_success',
  'mfa_otp_suspicious',
  'notification_sent',
  'otp_failed',
  'otp_success',
  'otp_suspicious',
  'recovery_otp_failed',
  'recovery_otp_success',
  'recovery_otp_suspicious',
  'refresh_token_failed',
  'refresh_token_success',
  'refresh_token_suspicious',
  'registration_failed',
  'registration_success',
  'registration_suspicious',
  'request_suspicious',
  'service_token_failed',
  'service_token_rotated',
  'service_token_success',
  'service_token_suspicious',
  'step_up_challenge',
  'step_up_failed',
  'step_up_success',
  'step_up_suspicious',
  'system_config_error',
  'system_config_read',
  'system_config_updated',
  'user_created',
  'user_data_failed',
  'user_data_success',
  'user_data_suspicious',
  'user_deleted',
  'verify_otp_failed',
  'verify_otp_success',
  'verify_otp_suspicious',
  'webauthn_login_failed',
  'webauthn_login_success',
  'webauthn_login_suspicious',
  'webauthn_registration_failed',
  'webauthn_registration_success',
  'webauthn_registration_suspicious',
] as const;

export const AuthEventTypeEnum = z.enum(AUTH_EVENT_TYPES);

export type AuthEventType = z.infer<typeof AuthEventTypeEnum>;
